version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
            - postgres_db
        networks:
            - default
        depends_on:
            - db
            - postgres_db
    db:
        image: mysql:5.7.13
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump/mysql:/docker-entrypoint-initdb.d
            - persistent_mysql:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    postgres_db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: myDb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: test
        volumes:
            - ./dump/postgres:/docker-entrypoint-initdb.d
            - persistent_postgres:/var/lib/postgresql/data
        networks:
            - default            
volumes:
    persistent_mysql:
    persistent_postgres: